# Generated by Django 2.2.3 on 2020-01-12 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='emp_name')),
                ('age', models.IntegerField(verbose_name='emp_age')),
                ('salary', models.FloatField(verbose_name='emp_sal')),
                ('position', models.CharField(max_length=100, verbose_name='emp_pos')),
                ('gender', models.CharField(max_length=100, verbose_name='emp_gen')),
                ('active', models.CharField(default='Y', max_length=100, verbose_name='emp_active')),
            ],
            managers=[
                ('allemps', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='adr_city')),
                ('state', models.CharField(max_length=100, verbose_name='adr_state')),
                ('pincode', models.CharField(max_length=100, verbose_name='adr_pin')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addrs', to='employee.EmpModel')),
            ],
        ),
    ]
